### ISSUE TITLE
刷新结束后header缩不回去

### ISSUE THREAD

**Issue by berial** [Loren-Moon/ComposeSmartRefresh#1]
下拉刷新后，数据请求完并将flag置为success，header仍然显示。
演示图是用直接用的库中的sample，为了能快速发现，是先上拉加载更多后，再下拉刷新的。实际依赖时，多次下拉会复现。
![](https://i.imgur.com/q0A0X3b.gif)

**Comment by Loren-Moon** [comment]
是设置的refreshFlag么，我demo没测试出这个bug，问问有详细的复现步骤吗

**Comment by berial** [comment]
没有任何花里胡哨的操作，先下拉刷新，再上拉加载，再下拉刷新，再上拉加载（此时就会一直显示正在加载）
用的是Android Studio的模拟器，demo代码只是把fillData的delay改成了1s加快演示。

**Comment by Loren-Moon** [comment]
已修正，多谢发现。
主要是因为LaunchedEffect(mainUiState.value)观测数据未改变所以无法处理后续流程了，真实项目不会出现类似的问题，因为数据都是请求回来是一个全新的data

**Comment by berial** [comment]
就很僵硬，我在项目中使用时，两次刷新后返回的数据确实是一样的，导致LaunchedEffect(xxxx)判断为未改变，这得自己加个时间戳类的字段，然后触发它？
----------------------
好吧，重写了equals和hashCode方法，改成了判断对象地址，修正了这个问题。

**Comment by Loren-Moon** [comment]
是有点麻烦，官方项目(JetNews)我看一般都是加个isLoading进行处理，加载中为true，加载完为false，这样就可以确保一定能触发副作用，可以看一下我新提交的代码
